cc_library(
    name = "aphttp",
    srcs = glob([
            "src/**",
            "include/**"
    ]),

    includes = [
            "include",
    ],

    hdrs = glob(["include/**"]),
    visibility = ["//visibility:public"],
)
